# -*- coding: utf-8 -*-
"""Oasis_DS_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F3asYR10vO_SwJny5dSDTMlY2EktSX6f
"""

# Commented out IPython magic to ensure Python compatibility.
# import all required libaries
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.linear_model import LogisticRegression as lr
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

irisdf = pd.read_csv("/content/Untitled Folder/Iris.csv")
#first 5 dataset
irisdf.head()

#last 5 dataset
irisdf.tail()

from IPython import display
display.Image("/content/pexels-scott-platt-8122418.jpg")

#description of dataset
irisdf.info()

# Dimension of data set
irisdf.shape

irisdf.size

#check for values of each species whether its balanced or imbalanced
irisdf['Species'].value_counts()

# Visualization in form of pie chart
irisdf['Species'].value_counts().plot(kind='pie',autopct='%.2f')

#Check if any null values is present in give dataset
irisdf.isnull().sum()

#Check for duplicate values
duplicate_count = irisdf.duplicated().sum()
print(duplicate_count)

#Scatter Plot to  visualize the datset
sns.FacetGrid(irisdf,hue='Species',height=4).map(plt.scatter,"SepalWidthCm" , "PetalLengthCm").add_legend()

plt.figure(figsize =(15,6))
sns.countplot(x='SepalLengthCm', data=irisdf, hue= irisdf['Species'], palette= 'winter')
plt.show()

plt.figure(figsize =(15,6))
sns.countplot(x='SepalWidthCm', data=irisdf, hue= irisdf['Species'], palette= 'autumn')
plt.show()

plt.figure(figsize =(15,6))
sns.countplot(x='PetalLengthCm', data=irisdf, hue= irisdf['Species'], palette= 'magma')
plt.show()

plt.figure(figsize =(15,6))
sns.countplot(x='PetalWidthCm', data=irisdf, hue= irisdf['Species'], palette= 'Blues')
plt.show()

#Coorelation matrix- if we have high correation then we can neglect one variables tht is positive correaltion i;e 0 to 1
irisdf.corr()

# Coor in form of heat map
corr = irisdf.corr()
sns.heatmap(corr,annot=True,cmap='Blues')

flower_mapping= {'Iris-setosa': 0, 'Iris-versicolor' : 1, 'Iris-virginica' :2}
irisdf['Species'] = irisdf ['Species'].map (flower_mapping)

irisdf.head()

irisdf.tail()

x=irisdf[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm','PetalWidthCm']].values
y=irisdf[['Species']].values

model = lr()

model.fit(x,y)

expected = y
predicted = model.predict(x)
predicted

print(metrics.classification_report(expected, predicted))

print(metrics.confusion_matrix(expected, predicted))

